# Code generated by sqlc. DO NOT EDIT.
# versions:
#   sqlc v1.27.0
import dataclasses
import datetime
from typing import List, Optional
import uuid


@dataclasses.dataclass()
class Attribute:
    id: int
    attribute_name: str
    attribute_value: str


@dataclasses.dataclass()
class Cart:
    id: uuid.UUID
    user_id: uuid.UUID
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class CartItem:
    id: uuid.UUID
    cart_id: uuid.UUID
    product_id: uuid.UUID
    quantity: int


@dataclasses.dataclass()
class GooseDbVersion:
    id: int
    version_id: int
    is_applied: bool
    tstamp: Optional[datetime.datetime]


@dataclasses.dataclass()
class Inventory:
    id: uuid.UUID
    variant_id: uuid.UUID
    seller_id: uuid.UUID
    quantity: int
    amount_units: int
    amount_nanos: int
    amount_currency: str


@dataclasses.dataclass()
class Location:
    id: uuid.UUID
    address: str
    city: str
    state: str
    country: str
    postal_code: str
    latitude: float
    longitude: float


@dataclasses.dataclass()
class Order:
    id: uuid.UUID
    user_id: uuid.UUID
    created_at: datetime.datetime
    updated_at: datetime.datetime
    amount_units: int
    amount_nanos: int
    amount_currency: str
    status: str
    payment_status: str


@dataclasses.dataclass()
class OrderItem:
    id: uuid.UUID
    order_id: uuid.UUID
    product_id: uuid.UUID
    seller_id: uuid.UUID
    quantity: int
    amount_units: int
    amount_nanos: int
    amount_currency: str
    status: str
    payment_status: str


@dataclasses.dataclass()
class Product:
    id: uuid.UUID
    product_name: Optional[str]
    category_id1: int
    category_id2: int
    category_id3: Optional[int]
    category_id4: Optional[int]


@dataclasses.dataclass()
class ProductAttribute:
    id: uuid.UUID
    product_id: uuid.UUID
    variant_id: Optional[uuid.UUID]
    attribute_id: int


@dataclasses.dataclass()
class ProductCategory:
    id: int
    name: str
    parent_id: Optional[int]


@dataclasses.dataclass()
class ProductComment:
    id: uuid.UUID
    comment: Optional[str]


@dataclasses.dataclass()
class ProductDescription:
    id: uuid.UUID
    product_id: uuid.UUID
    variant_id: Optional[uuid.UUID]
    description: Optional[str]
    images: Optional[List[str]]
    videos: Optional[List[str]]


@dataclasses.dataclass()
class ProductPromotion:
    id: uuid.UUID
    variant_id: uuid.UUID
    promotion_name: str
    discount: int
    start_date: datetime.date
    end_date: datetime.date


@dataclasses.dataclass()
class ProductReview:
    id: uuid.UUID
    user_id: uuid.UUID
    product_id: uuid.UUID
    seller_id: uuid.UUID
    rating: int
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class ProductVariant:
    id: uuid.UUID
    product_id: uuid.UUID
    variant_name: str


@dataclasses.dataclass()
class Seller:
    id: uuid.UUID
    name: str
    location: Optional[uuid.UUID]
    created_at: datetime.datetime
    updated_at: datetime.datetime


@dataclasses.dataclass()
class User:
    id: uuid.UUID
    username: Optional[str]
    password_hash: Optional[str]
    email: Optional[str]
    verified: bool
    phone_number: Optional[str]
    avatar: Optional[uuid.UUID]
    gender: Optional[str]
    role: int
    date_of_birth: Optional[datetime.date]
    location: Optional[uuid.UUID]
    created_at: datetime.datetime
    updated_at: datetime.datetime
