// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: cosmog/v1/cosmog.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSearchKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSearchKeyRequest) Reset() {
	*x = CreateSearchKeyRequest{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSearchKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSearchKeyRequest) ProtoMessage() {}

func (x *CreateSearchKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSearchKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateSearchKeyRequest) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSearchKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateSearchKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSearchKeyResponse) Reset() {
	*x = CreateSearchKeyResponse{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSearchKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSearchKeyResponse) ProtoMessage() {}

func (x *CreateSearchKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSearchKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateSearchKeyResponse) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSearchKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{2}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lvl0          string                 `protobuf:"bytes,1,opt,name=lvl0,proto3" json:"lvl0,omitempty"`
	Lvl1          string                 `protobuf:"bytes,2,opt,name=lvl1,proto3" json:"lvl1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{3}
}

func (x *Category) GetLvl0() string {
	if x != nil {
		return x.Lvl0
	}
	return ""
}

func (x *Category) GetLvl1() string {
	if x != nil {
		return x.Lvl1
	}
	return ""
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Info          string                 `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Category      *Category              `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Rating        float32                `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Dev           string                 `protobuf:"bytes,7,opt,name=dev,proto3" json:"dev,omitempty"`
	Brand         string                 `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Img           []string               `protobuf:"bytes,9,rep,name=img,proto3" json:"img,omitempty"`
	Mov           []string               `protobuf:"bytes,10,rep,name=mov,proto3" json:"mov,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{4}
}

func (x *Product) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Product) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *Product) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Product) GetDev() string {
	if x != nil {
		return x.Dev
	}
	return ""
}

func (x *Product) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *Product) GetImg() []string {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *Product) GetMov() []string {
	if x != nil {
		return x.Mov
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taskid        int32                  `protobuf:"varint,1,opt,name=taskid,proto3" json:"taskid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteProductResponse) GetTaskid() int32 {
	if x != nil {
		return x.Taskid
	}
	return 0
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Info          string                 `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Category      *Category              `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Rating        float32                `protobuf:"fixed32,6,opt,name=rating,proto3" json:"rating,omitempty"`
	Dev           string                 `protobuf:"bytes,7,opt,name=dev,proto3" json:"dev,omitempty"`
	Brand         string                 `protobuf:"bytes,8,opt,name=brand,proto3" json:"brand,omitempty"`
	Img           []string               `protobuf:"bytes,9,rep,name=img,proto3" json:"img,omitempty"`
	Mov           []string               `protobuf:"bytes,10,rep,name=mov,proto3" json:"mov,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProductRequest) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *UpdateProductRequest) GetCategory() *Category {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *UpdateProductRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateProductRequest) GetRating() float32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *UpdateProductRequest) GetDev() string {
	if x != nil {
		return x.Dev
	}
	return ""
}

func (x *UpdateProductRequest) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *UpdateProductRequest) GetImg() []string {
	if x != nil {
		return x.Img
	}
	return nil
}

func (x *UpdateProductRequest) GetMov() []string {
	if x != nil {
		return x.Mov
	}
	return nil
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taskid        int32                  `protobuf:"varint,1,opt,name=taskid,proto3" json:"taskid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateProductResponse) GetTaskid() int32 {
	if x != nil {
		return x.Taskid
	}
	return 0
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Taskid        int32                  `protobuf:"varint,1,opt,name=taskid,proto3" json:"taskid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskRequest) GetTaskid() int32 {
	if x != nil {
		return x.Taskid
	}
	return 0
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cosmog_v1_cosmog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_cosmog_v1_cosmog_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GetTaskResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *GetTaskResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_cosmog_v1_cosmog_proto protoreflect.FileDescriptor

const file_cosmog_v1_cosmog_proto_rawDesc = "" +
	"\n" +
	"\x16cosmog/v1/cosmog.proto\x12\tcosmog.v1\x1a\x1bbuf/validate/validate.proto\"2\n" +
	"\x16CreateSearchKeyRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"+\n" +
	"\x17CreateSearchKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"-\n" +
	"\x11GetProductRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"2\n" +
	"\bCategory\x12\x12\n" +
	"\x04lvl0\x18\x01 \x01(\tR\x04lvl0\x12\x12\n" +
	"\x04lvl1\x18\x02 \x01(\tR\x04lvl1\"\xf8\x01\n" +
	"\aProduct\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\x12/\n" +
	"\bcategory\x18\x04 \x01(\v2\x13.cosmog.v1.CategoryR\bcategory\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x02R\x06rating\x12\x10\n" +
	"\x03dev\x18\a \x01(\tR\x03dev\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x10\n" +
	"\x03img\x18\t \x03(\tR\x03img\x12\x10\n" +
	"\x03mov\x18\n" +
	" \x03(\tR\x03mov\"0\n" +
	"\x14DeleteProductRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\"/\n" +
	"\x15DeleteProductResponse\x12\x16\n" +
	"\x06taskid\x18\x01 \x01(\x05R\x06taskid\"\x85\x02\n" +
	"\x14UpdateProductRequest\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\x12/\n" +
	"\bcategory\x18\x04 \x01(\v2\x13.cosmog.v1.CategoryR\bcategory\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x16\n" +
	"\x06rating\x18\x06 \x01(\x02R\x06rating\x12\x10\n" +
	"\x03dev\x18\a \x01(\tR\x03dev\x12\x14\n" +
	"\x05brand\x18\b \x01(\tR\x05brand\x12\x10\n" +
	"\x03img\x18\t \x03(\tR\x03img\x12\x10\n" +
	"\x03mov\x18\n" +
	" \x03(\tR\x03mov\"/\n" +
	"\x15UpdateProductResponse\x12\x16\n" +
	"\x06taskid\x18\x01 \x01(\x05R\x06taskid\"(\n" +
	"\x0eGetTaskRequest\x12\x16\n" +
	"\x06taskid\x18\x01 \x01(\x05R\x06taskid\"]\n" +
	"\x0fGetTaskResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\x12\x1c\n" +
	"\terrorCode\x18\x02 \x01(\tR\terrorCode\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status2\x93\x03\n" +
	"\rCosmogService\x12X\n" +
	"\x0fCreateSearchKey\x12!.cosmog.v1.CreateSearchKeyRequest\x1a\".cosmog.v1.CreateSearchKeyResponse\x12>\n" +
	"\n" +
	"GetProduct\x12\x1c.cosmog.v1.GetProductRequest\x1a\x12.cosmog.v1.Product\x12R\n" +
	"\rDeleteProduct\x12\x1f.cosmog.v1.DeleteProductRequest\x1a .cosmog.v1.DeleteProductResponse\x12R\n" +
	"\rUpdateProduct\x12\x1f.cosmog.v1.UpdateProductRequest\x1a .cosmog.v1.UpdateProductResponse\x12@\n" +
	"\aGetTask\x12\x19.cosmog.v1.GetTaskRequest\x1a\x1a.cosmog.v1.GetTaskResponseB\x95\x01\n" +
	"\rcom.cosmog.v1B\vCosmogProtoP\x01Z2github.com/codeharik/Atlantic/cosmog/api/cosmog/v1\xa2\x02\x03CXX\xaa\x02\tCosmog.V1\xca\x02\tCosmog\\V1\xe2\x02\x15Cosmog\\V1\\GPBMetadata\xea\x02\n" +
	"Cosmog::V1b\x06proto3"

var (
	file_cosmog_v1_cosmog_proto_rawDescOnce sync.Once
	file_cosmog_v1_cosmog_proto_rawDescData []byte
)

func file_cosmog_v1_cosmog_proto_rawDescGZIP() []byte {
	file_cosmog_v1_cosmog_proto_rawDescOnce.Do(func() {
		file_cosmog_v1_cosmog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cosmog_v1_cosmog_proto_rawDesc), len(file_cosmog_v1_cosmog_proto_rawDesc)))
	})
	return file_cosmog_v1_cosmog_proto_rawDescData
}

var file_cosmog_v1_cosmog_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cosmog_v1_cosmog_proto_goTypes = []any{
	(*CreateSearchKeyRequest)(nil),  // 0: cosmog.v1.CreateSearchKeyRequest
	(*CreateSearchKeyResponse)(nil), // 1: cosmog.v1.CreateSearchKeyResponse
	(*GetProductRequest)(nil),       // 2: cosmog.v1.GetProductRequest
	(*Category)(nil),                // 3: cosmog.v1.Category
	(*Product)(nil),                 // 4: cosmog.v1.Product
	(*DeleteProductRequest)(nil),    // 5: cosmog.v1.DeleteProductRequest
	(*DeleteProductResponse)(nil),   // 6: cosmog.v1.DeleteProductResponse
	(*UpdateProductRequest)(nil),    // 7: cosmog.v1.UpdateProductRequest
	(*UpdateProductResponse)(nil),   // 8: cosmog.v1.UpdateProductResponse
	(*GetTaskRequest)(nil),          // 9: cosmog.v1.GetTaskRequest
	(*GetTaskResponse)(nil),         // 10: cosmog.v1.GetTaskResponse
}
var file_cosmog_v1_cosmog_proto_depIdxs = []int32{
	3,  // 0: cosmog.v1.Product.category:type_name -> cosmog.v1.Category
	3,  // 1: cosmog.v1.UpdateProductRequest.category:type_name -> cosmog.v1.Category
	0,  // 2: cosmog.v1.CosmogService.CreateSearchKey:input_type -> cosmog.v1.CreateSearchKeyRequest
	2,  // 3: cosmog.v1.CosmogService.GetProduct:input_type -> cosmog.v1.GetProductRequest
	5,  // 4: cosmog.v1.CosmogService.DeleteProduct:input_type -> cosmog.v1.DeleteProductRequest
	7,  // 5: cosmog.v1.CosmogService.UpdateProduct:input_type -> cosmog.v1.UpdateProductRequest
	9,  // 6: cosmog.v1.CosmogService.GetTask:input_type -> cosmog.v1.GetTaskRequest
	1,  // 7: cosmog.v1.CosmogService.CreateSearchKey:output_type -> cosmog.v1.CreateSearchKeyResponse
	4,  // 8: cosmog.v1.CosmogService.GetProduct:output_type -> cosmog.v1.Product
	6,  // 9: cosmog.v1.CosmogService.DeleteProduct:output_type -> cosmog.v1.DeleteProductResponse
	8,  // 10: cosmog.v1.CosmogService.UpdateProduct:output_type -> cosmog.v1.UpdateProductResponse
	10, // 11: cosmog.v1.CosmogService.GetTask:output_type -> cosmog.v1.GetTaskResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_cosmog_v1_cosmog_proto_init() }
func file_cosmog_v1_cosmog_proto_init() {
	if File_cosmog_v1_cosmog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cosmog_v1_cosmog_proto_rawDesc), len(file_cosmog_v1_cosmog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cosmog_v1_cosmog_proto_goTypes,
		DependencyIndexes: file_cosmog_v1_cosmog_proto_depIdxs,
		MessageInfos:      file_cosmog_v1_cosmog_proto_msgTypes,
	}.Build()
	File_cosmog_v1_cosmog_proto = out.File
	file_cosmog_v1_cosmog_proto_goTypes = nil
	file_cosmog_v1_cosmog_proto_depIdxs = nil
}
