// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file cosmog/v1/cosmog.proto (package cosmog.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateSearchKeyRequest, CreateSearchKeyResponse } from "./cosmog_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service cosmog.v1.CosmogService
 */
export const CosmogService = {
  typeName: "cosmog.v1.CosmogService",
  methods: {
    /**
     * @generated from rpc cosmog.v1.CosmogService.CreateSearchKey
     */
    createSearchKey: {
      name: "CreateSearchKey",
      I: CreateSearchKeyRequest,
      O: CreateSearchKeyResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

