// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect).

package inventory

import (
	"github.com/codeharik/Atlantic/database/api/inventory/v1/v1connect"
)

// NewService is a constructor of a v1.InventoryServiceHandler implementation.
// Use this function to customize the server by adding middlewares to it.
func NewService(querier *Queries) v1connect.InventoryServiceHandler {
	return &Service{querier: querier}
}
