name: atlantic
services:
  cosmog:
    build:
      context: /Users/Shared/Go/Atlantic
      dockerfile: Dockerfile.cosmog
    image: cosmog:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 7800
        published: "7800"
        protocol: tcp
  skitty:
    build:
      context: /Users/Shared/Go/Atlantic
      dockerfile: Dockerfile.skitty
      args:
        VITE_HOST: http://localhost
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: "268435456"
    image: skitty:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 3000
        published: "3000"
        protocol: tcp
networks:
  default:
    name: atlantic
    driver: bridge
