# Use the official Alpine base image
FROM alpine:latest

RUN apk update && \
    apk add --no-cache \
        postgresql-client \
        bind-tools \
        curl \
        iputils \
        bash \
        && rm -rf /var/cache/apk/*

ENV PGHOST=postgres
ENV PGUSER=superuser
ENV PGDATABASE=test
ENV PGPASSWORD=secret

WORKDIR /app

CMD ["sh", "-c", "while :; do sleep 3600; done"]
