FROM golang:1.23.1-alpine3.20 AS build-stage

WORKDIR /app

COPY . .

RUN cd inventory

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o ../inventory ./inventory/cmd

FROM build-stage AS run-test-stage
RUN go test -v ./...

FROM cgr.dev/chainguard/static:latest

WORKDIR /

COPY --from=build-stage /inventory /inventory
COPY --from=build-stage /app/config/config.json .

EXPOSE 7777

CMD ["./inventory"]
