name: atlantic
services:
  postgres:
    profiles:
      - docker
    command:
      - -c
      - config_file=/etc/postgresql/postgresql.conf
    container_name: postgres
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: superuser
    image: cgr.dev/chainguard/postgres:latest
    labels:
      kompose.volume.size: 1Gi
    networks:
      default: null
    ports:
      - mode: ingress
        target: 5432
        published: "5432"
        protocol: tcp
    restart: always
    volumes:
      - type: volume
        source: pg-data
        target: /var/lib/postgresql/data
        volume: {}
      - type: bind
        source: /Users/Shared/Go/Atlantic/config/postgres/postgresql.conf
        target: /etc/postgresql/postgresql.conf
        bind:
          create_host_path: true
  test:
    build:
      context: /Users/Shared/Go/Atlantic
      dockerfile: Dockerfile.test
    environment:
      PGPASSWORD: secret
      POSTGRES_DB: test
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: superuser
    image: test:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 15155
        published: "15155"
        protocol: tcp
networks:
  default:
    name: atlantic
    driver: bridge
volumes:
  pg-data:
    name: atlantic_pg-data
