name: atlantic
services:
  test:
    build:
      context: /Users/Shared/Go/Atlantic
      dockerfile: Dockerfile.test
    environment:
      PGPASSWORD: secret
      POSTGRES_DB: test
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: superuser
    image: test:v0.0.1
    networks:
      default: null
    ports:
      - mode: ingress
        target: 15155
        published: "15155"
        protocol: tcp
networks:
  default:
    name: atlantic
    driver: bridge
