apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: atlantic
build:
  artifacts:
    # - image: auth
    #   docker:
    #     dockerfile: Dockerfile.auth

    - image: skitty
      docker:
        dockerfile: Dockerfile.skitty

    - image: cosmog
      docker:
        dockerfile: Dockerfile.cosmog

  # - image: skitty
  #   ko:
  #     dependencies:
  #       paths:
  #       - "**/*.go"
  #       - go.*
  #       - kodata/**/*
  #     fromImage: gcr.io/distroless/static-debian11:nonroot
  #   sync:
  #     infer:
  #     - kodata/**/*

manifests:
  rawYaml:
    - k8s/add/*.yaml
    - k8s/gen/*.yaml
portForward:
- resourceType: service
  resourceName: skitty
  namespace: default
  port: 3000
  localPort: 3000