apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: atlantic
build:
  artifacts:
    - image: auth
      context: auth
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
    - image: skitty
      context: skitty
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - k8s/_atlantic.yaml
    - k8s/_config.yaml
    - k8s/auth-service.yaml
    - k8s/skitty-service.yaml
