apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: atlantic
build:
  artifacts:
    # - image: auth
    #   docker:
    #     dockerfile: Dockerfile.auth

    - image: skitty
      docker:
        dockerfile: Dockerfile.skitty


manifests:
  rawYaml:
    - k8s/_atlantic.yaml
    - k8s/_config.yaml
    # - k8s/auth-cm0-configmap.yaml
    # - k8s/auth-deployment.yaml
    # - k8s/auth-horizontalpodautoscaler.yaml
    # - k8s/auth-service.yaml
    # - k8s/pg-data-persistentvolumeclaim.yaml
    # - k8s/postgres-cm1-configmap.yaml
    # - k8s/postgres-deployment.yaml
    # - k8s/postgres-service.yaml
    - k8s/skitty-deployment.yaml
    - k8s/skitty-service.yaml
    - k8s/tcpdump-deployment.yaml
portForward:
- resourceType: service
  resourceName: skitty
  namespace: default
  port: 3000
  localPort: 3000