apiVersion: skaffold/v4beta11
kind: Config
metadata:
   name: atlantic
# build:
#    artifacts:
#       # - image: test
#       #   docker:
#       #      dockerfile: Dockerfile.test

#       # - image: auth
#       #   docker:
#       #     dockerfile: Dockerfile.auth

#       # - image: skitty
#       #   docker:
#       #     dockerfile: Dockerfile.skitty
#       #     buildArgs:
#       #       VITE_DOMAIN: http://localhost

#       # - image: cosmog
#       #   docker:
#       #     dockerfile: Dockerfile.cosmog

#       # - image: skitty
#       #   ko:
#       #      dir: ./skitty
#       #   flags:
#       #     - -mod=vendor
#       #     - -v
#       #   dependencies:
#       #     paths:
#       #       - skitty/**.go
#       #       - skitty/kodata/**/*
#       # fromImage: cgr.dev/chainguard/static:latest
#       # sync:
#       #   infer:
#       #     - skitty/kodata/**/*

deploy:
   helm:
      releases:
         - name: argo
           repo: https://argoproj.github.io/argo-helm
           remoteChart: argo-cd
           version: 7.5.2
           namespace: argocd
           createNamespace: true
           valuesFiles:
              - k8s/values/argo.yaml
manifests:
   rawYaml:
      # - k8s/argo/argo-certmanager.yaml

      # - k8s/argo/argo-sealed-secrets.yaml
      # - k8s/argo/argo-dragon.yaml
      # - k8s/argo/argo-minio.yaml
      # - k8s/argo/argo-postgres.yaml
      # - k8s/argo/argo-nats.yaml
      # - k8s/argo/argo-headlamp.yaml

      # - k8s/gen/*.yaml
      # - k8s/add/*.yaml

      - clonek7s/quickstart.yaml
# portForward:
#    - resourceType: service
#      resourceName: skitty
#      namespace: atlantic
#      port: 3000
#      localPort: 3000
#    # - resourceType: service
#    #   resourceName: cosmog
#    #   namespace: atlantic
#    #   port: 7800
#    #   localPort: 7800
