// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file product/v1/product.proto (package product.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CheckProductQuantityRequest, CheckProductQuantityResponse, CreateProductRequest, CreateProductResponse, DeleteProductRequest, DeleteProductResponse, GetProductByIDRequest, GetProductByIDResponse, ListProductsRequest, ListProductsResponse, UpdateProductRequest, UpdateProductResponse } from "./product_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service product.v1.ProductService
 */
export const ProductService = {
  typeName: "product.v1.ProductService",
  methods: {
    /**
     * @generated from rpc product.v1.ProductService.CheckProductQuantity
     */
    checkProductQuantity: {
      name: "CheckProductQuantity",
      I: CheckProductQuantityRequest,
      O: CheckProductQuantityResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.v1.ProductService.CreateProduct
     */
    createProduct: {
      name: "CreateProduct",
      I: CreateProductRequest,
      O: CreateProductResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.v1.ProductService.DeleteProduct
     */
    deleteProduct: {
      name: "DeleteProduct",
      I: DeleteProductRequest,
      O: DeleteProductResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.v1.ProductService.GetProductByID
     */
    getProductByID: {
      name: "GetProductByID",
      I: GetProductByIDRequest,
      O: GetProductByIDResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.v1.ProductService.ListProducts
     */
    listProducts: {
      name: "ListProducts",
      I: ListProductsRequest,
      O: ListProductsResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc product.v1.ProductService.UpdateProduct
     */
    updateProduct: {
      name: "UpdateProduct",
      I: UpdateProductRequest,
      O: UpdateProductResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

