FROM golang:1.23rc2-alpine3.20 AS build-stage

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /auth ./cmd

FROM build-stage AS run-test-stage
RUN go test -v ./...

FROM alpine:latest

WORKDIR /

COPY --from=build-stage /auth /auth
# COPY --from=build-stage /app/config.json .

EXPOSE 7777

CMD ["./auth"]