run:
	python3 main.py
app:
	streamlit run app.py
format:
	ruff format .
shell:
	poetry shell
	poetry env info --path

env:
	conda env list
	conda env export > environment.yml
install:
	conda install -c conda-forge streamlit altair
