// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: product.sql

package product

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO
    products (
        id,
        product_name,
        category_id1,
        category_id2
    )
VALUES ($1, $2, $3, $4) RETURNING id
`

type CreateProductParams struct {
	ID          uuid.UUID   `json:"id"`
	ProductName pgtype.Text `json:"product_name"`
	CategoryId1 int32       `json:"category_id1"`
	CategoryId2 int32       `json:"category_id2"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.ID,
		arg.ProductName,
		arg.CategoryId1,
		arg.CategoryId2,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, product_name, category_id1, category_id2 FROM products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.ProductName,
		&i.CategoryId1,
		&i.CategoryId2,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, product_name, category_id1, category_id2 FROM products ORDER BY id LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.ProductName,
			&i.CategoryId1,
			&i.CategoryId2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products
SET
    product_name = $2,
    category_id1 = $3,
    category_id2 = $4
WHERE
    id = $1
`

type UpdateProductParams struct {
	ID          uuid.UUID   `json:"id"`
	ProductName pgtype.Text `json:"product_name"`
	CategoryId1 int32       `json:"category_id1"`
	CategoryId2 int32       `json:"category_id2"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.ProductName,
		arg.CategoryId1,
		arg.CategoryId2,
	)
	return err
}
