// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file inventory/v1/inventory.proto (package inventory.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message inventory.v1.UploadImageRequest
 */
export class UploadImageRequest extends Message<UploadImageRequest> {
  constructor(data?: PartialMessage<UploadImageRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "inventory.v1.UploadImageRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadImageRequest {
    return new UploadImageRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadImageRequest {
    return new UploadImageRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadImageRequest {
    return new UploadImageRequest().fromJsonString(jsonString, options);
  }

  static equals(a: UploadImageRequest | PlainMessage<UploadImageRequest> | undefined, b: UploadImageRequest | PlainMessage<UploadImageRequest> | undefined): boolean {
    return proto3.util.equals(UploadImageRequest, a, b);
  }
}

/**
 * @generated from message inventory.v1.UploadImageResponse
 */
export class UploadImageResponse extends Message<UploadImageResponse> {
  constructor(data?: PartialMessage<UploadImageResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "inventory.v1.UploadImageResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UploadImageResponse {
    return new UploadImageResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UploadImageResponse {
    return new UploadImageResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UploadImageResponse {
    return new UploadImageResponse().fromJsonString(jsonString, options);
  }

  static equals(a: UploadImageResponse | PlainMessage<UploadImageResponse> | undefined, b: UploadImageResponse | PlainMessage<UploadImageResponse> | undefined): boolean {
    return proto3.util.equals(UploadImageResponse, a, b);
  }
}

