// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file inventory/v1/inventory.proto (package inventory.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file inventory/v1/inventory.proto.
 */
export const file_inventory_v1_inventory: GenFile = /*@__PURE__*/
  fileDesc("ChxpbnZlbnRvcnkvdjEvaW52ZW50b3J5LnByb3RvEgxpbnZlbnRvcnkudjEyEgoQSW52ZW50b3J5U2VydmljZUKtAQoQY29tLmludmVudG9yeS52MUIOSW52ZW50b3J5UHJvdG9QAVo4Z2l0aHViLmNvbS9jb2RlaGFyaWsvQXRsYW50aWMvaW52ZW50b3J5L2FwaS9pbnZlbnRvcnkvdjGiAgNJWFiqAgxJbnZlbnRvcnkuVjHKAgxJbnZlbnRvcnlcVjHiAhhJbnZlbnRvcnlcVjFcR1BCTWV0YWRhdGHqAg1JbnZlbnRvcnk6OlYxYgZwcm90bzM");

/**
 * @generated from service inventory.v1.InventoryService
 */
export const InventoryService: GenService<{
}> = /*@__PURE__*/
  serviceDesc(file_inventory_v1_inventory, 0);

