// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect). DO NOT EDIT.

package seller

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"

	"connectrpc.com/connect"
	"github.com/google/uuid"

	pb "github.com/codeharik/Atlantic/database/api/seller/v1"
	"github.com/codeharik/Atlantic/database/api/seller/v1/v1connect"
	"github.com/codeharik/Atlantic/database/internal/validation"
)

type Service struct {
	v1connect.UnimplementedSellerServiceHandler
	querier *Queries
}

func (s *Service) CreateSeller(ctx context.Context, req *connect.Request[pb.CreateSellerRequest]) (*connect.Response[pb.CreateSellerResponse], error) {
	var arg CreateSellerParams
	if v, err := uuid.Parse(req.Msg.GetId()); err != nil {
		err = fmt.Errorf("invalid ID: %s%w", err.Error(), validation.ErrUserInput)
		return nil, err
	} else {
		arg.ID = v
	}
	arg.Name = req.Msg.GetName()
	if v := req.Msg.GetLocation(); v != nil {
		if err := json.Unmarshal([]byte(v.String()), &arg.Location); err != nil {
			err = fmt.Errorf("invalid Location: %s%w", err.Error(), validation.ErrUserInput)
			return nil, err
		}
	}

	result, err := s.querier.CreateSeller(ctx, arg)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "CreateSeller")
		return nil, err
	}
	return connect.NewResponse(&pb.CreateSellerResponse{CreateSellerRow: toCreateSellerRow(result)}), nil
}

func (s *Service) DeleteSeller(ctx context.Context, req *connect.Request[pb.DeleteSellerRequest]) (*connect.Response[pb.DeleteSellerResponse], error) {
	var id uuid.UUID
	if v, err := uuid.Parse(req.Msg.GetId()); err != nil {
		err = fmt.Errorf("invalid Id: %s%w", err.Error(), validation.ErrUserInput)
		return nil, err
	} else {
		id = v
	}

	err := s.querier.DeleteSeller(ctx, id)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "DeleteSeller")
		return nil, err
	}
	return connect.NewResponse(&pb.DeleteSellerResponse{}), nil
}

func (s *Service) GetSellerByID(ctx context.Context, req *connect.Request[pb.GetSellerByIDRequest]) (*connect.Response[pb.GetSellerByIDResponse], error) {
	var id uuid.UUID
	if v, err := uuid.Parse(req.Msg.GetId()); err != nil {
		err = fmt.Errorf("invalid Id: %s%w", err.Error(), validation.ErrUserInput)
		return nil, err
	} else {
		id = v
	}

	result, err := s.querier.GetSellerByID(ctx, id)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "GetSellerByID")
		return nil, err
	}
	return connect.NewResponse(&pb.GetSellerByIDResponse{GetSellerByIdRow: toGetSellerByIDRow(result)}), nil
}

func (s *Service) ListSellers(ctx context.Context, req *connect.Request[pb.ListSellersRequest]) (*connect.Response[pb.ListSellersResponse], error) {

	result, err := s.querier.ListSellers(ctx)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "ListSellers")
		return nil, err
	}
	res := new(pb.ListSellersResponse)
	for _, r := range result {
		res.List = append(res.List, toListSellersRow(r))
	}
	return connect.NewResponse(res), nil
}

func (s *Service) UpdateSeller(ctx context.Context, req *connect.Request[pb.UpdateSellerRequest]) (*connect.Response[pb.UpdateSellerResponse], error) {
	var arg UpdateSellerParams
	if v, err := uuid.Parse(req.Msg.GetId()); err != nil {
		err = fmt.Errorf("invalid ID: %s%w", err.Error(), validation.ErrUserInput)
		return nil, err
	} else {
		arg.ID = v
	}
	arg.Name = req.Msg.GetName()
	if v := req.Msg.GetLocation(); v != nil {
		if err := json.Unmarshal([]byte(v.String()), &arg.Location); err != nil {
			err = fmt.Errorf("invalid Location: %s%w", err.Error(), validation.ErrUserInput)
			return nil, err
		}
	}

	err := s.querier.UpdateSeller(ctx, arg)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "UpdateSeller")
		return nil, err
	}
	return connect.NewResponse(&pb.UpdateSellerResponse{}), nil
}
