apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: atlantic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth:latest # Replace with your actual image
        restartPolicy: Always
        ports:
          - containerPort: 7777
        resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
        volumeMounts:
        - name: config-volume
          mountPath: /config.json
          subPath: config.json
      volumes:
      - name: config-volume
        configMap:
          name: atlantic-config
      
      # postgres dependency can be handled with startup probes or init containers, depending on your setup

---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: atlantic
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
  type: ClusterIP
