apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    org: AtlanticSpaceship
  labels:
    io.kompose.service: auth
  name: auth
  namespace: atlantic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        org: AtlanticSpaceship
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: DATABASE_DBNAME
              value: test
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PASSWORD
              value: secret
            - name: DATABASE_SSLMODE
              value: disable
            - name: DATABASE_USER
              value: superuser
          image: auth:v0.0.1
          name: auth
          ports:
            - containerPort: 7777
              protocol: TCP
          volumeMounts:
            - mountPath: /run/secrets
              name: my-secret
              subPath: my-secret
            - mountPath: /config.json
              name: auth-cm0
              subPath: config.json
      restartPolicy: Always
      volumes:
        - name: my-secret
          secret:
            items:
              - key: my-secret
                path: my-secret
            secretName: my-secret
        - configMap:
            items:
              - key: config.json
                path: config.json
            name: auth-cm0
          name: auth-cm0
