apiVersion: v1
kind: Service
metadata:
  annotations:
    org: AtlanticSpaceship
  labels:
    io.kompose.service: auth
  name: auth
  namespace: atlantic
spec:
  ports:
    - name: "7777"
      port: 7777
      targetPort: 7777
  selector:
    io.kompose.service: auth
  type: ClusterIP
