apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: caddy
  name: caddy
  namespace: atlantic
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caddy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: caddy
    spec:
      containers:
        - args:
            - run
            - --config
            - /etc/caddy/Caddyfile
          image: cgr.dev/chainguard/caddy:latest
          name: caddy
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: caddy-cm0
              subPath: Caddyfile
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: CaddyfileDocker
                path: Caddyfile
            name: caddy-cm0
          name: caddy-cm0
