apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/shark/.asdf/installs/kompose/1.34.0/bin/kompose convert -f docker-compose.k8s.yaml -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
  selector:
    io.kompose.service: caddy
