apiVersion: v1
data:
  CaddyfileDocker: |
    localhost:80 {
    	# Reverse proxy for specific services
    	reverse_proxy /inventory.v1.InventoryService/* inventory:9100
    	reverse_proxy /profile.v1.ProfileService/* auth:7777
    	reverse_proxy /auth.v1.AuthService/* auth:7777

    	# Forward all other requests to the Next.js server
    	reverse_proxy /* skitty:3000
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: caddy
  name: caddy-cm0
