apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/shark/.asdf/installs/kompose/1.34.0/bin/kompose convert -f docker-compose.yaml -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caddy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/shark/.asdf/installs/kompose/1.34.0/bin/kompose convert -f docker-compose.yaml -o k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: caddy
    spec:
      containers:
        - args:
            - run
            - --config
            - /etc/caddy/Caddyfile
          image: cgr.dev/chainguard/caddy:latest
          name: caddy
          ports:
            - containerPort: 80
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: caddy-cm0
              subPath: Caddyfile
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: CaddyfileDocker
                path: Caddyfile
            name: caddy-cm0
          name: caddy-cm0
