apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: /Users/shark/.asdf/installs/kompose/1.34.0/bin/kompose convert -f docker-compose.yaml -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: goose-migration
  name: goose-migration
spec:
  containers:
    - command:
        - /bin/sh
        - -c
        - goose -dir /migrations postgres postgres://superuser:secret@postgres:5432/test?sslmode=disable up
      env:
        - name: DATABASE_URL
          value: postgres://superuser:secret@postgres:5432/test?sslmode=disable
      image: goose-migration
      name: goose-migration
      volumeMounts:
        - mountPath: /migrations
          name: goose-migration-cm0
  restartPolicy: OnFailure
  volumes:
    - configMap:
        name: goose-migration-cm0
      name: goose-migration-cm0
