apiVersion: v1
data:
  my-secret: VEFHPXYwLjAuMQoKU0tJVFRZX0NQVV9MSU1JVD0wLjUKU0tJVFRZX01FTU9SWV9MSU1JVD0yNTZNCgpEQVRBQkFTRV9IT1NUPXBvc3RncmVzCg==
kind: Secret
metadata:
  labels:
    io.kompose.service: my-secret
  name: my-secret
  namespace: atlantic
type: Opaque
