apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/shark/.asdf/installs/kompose/1.34.0/bin/kompose convert -f docker-compose.k8s.yaml -o k8s
    kompose.version: 1.34.0 (cbf2835db)
    kompose.volume.size: 1Gi
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/shark/.asdf/installs/kompose/1.34.0/bin/kompose convert -f docker-compose.k8s.yaml -o k8s
        kompose.version: 1.34.0 (cbf2835db)
        kompose.volume.size: 1Gi
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - args:
            - -c
            - config_file=/etc/postgresql/postgresql.conf
          env:
            - name: POSTGRES_DB
              value: test
            - name: POSTGRES_PASSWORD
              value: secret
            - name: POSTGRES_USER
              value: superuser
          image: cgr.dev/chainguard/postgres:latest
          name: postgres
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
            - mountPath: /etc/postgresql/postgresql.conf
              name: postgres-cm1
              subPath: postgresql.conf
      restartPolicy: Always
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: pg-data
        - configMap:
            items:
              - key: postgresql.conf
                path: postgresql.conf
            name: postgres-cm1
          name: postgres-cm1
