apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: /Users/shark/.asdf/installs/kompose/1.34.0/bin/kompose convert -f docker-compose.yaml -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: skitty
  name: skitty
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: skitty
