apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /Users/shark/.asdf/installs/kompose/1.34.0/bin/kompose convert -f docker-compose.yaml -o k8s
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: skitty
  name: skitty
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: skitty
  template:
    metadata:
      annotations:
        kompose.cmd: /Users/shark/.asdf/installs/kompose/1.34.0/bin/kompose convert -f docker-compose.yaml -o k8s
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: skitty
    spec:
      containers:
        - env:
            - name: DEBUG
              value: debug-mode
          image: skitty
          name: skitty
          ports:
            - containerPort: 3000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: "268435456"
      restartPolicy: Always
