// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file account/v1/accounts.proto (package account.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddBalanceRequest, AddBalanceResponse } from "./accounts_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service account.v1.AccountService
 */
export const AccountService = {
  typeName: "account.v1.AccountService",
  methods: {
    /**
     * @generated from rpc account.v1.AccountService.AddBalance
     */
    addBalance: {
      name: "AddBalance",
      I: AddBalanceRequest,
      O: AddBalanceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

