// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: product.sql

package product

import (
	"context"
)

const createProductAndDescription = `-- name: CreateProductAndDescription :one
BEGIN
`

type CreateProductAndDescriptionRow struct {
}

func (q *Queries) CreateProductAndDescription(ctx context.Context) (CreateProductAndDescriptionRow, error) {
	row := q.db.QueryRow(ctx, createProductAndDescription)
	var i CreateProductAndDescriptionRow
	err := row.Scan()
	return i, err
}
