// Code generated by sqlc-connect (https://github.com/walterwanderley/sqlc-connect). DO NOT EDIT.

package product

import (
	"context"
	"log/slog"

	"connectrpc.com/connect"

	pb "github.com/codeharik/Atlantic/sandslash/api/product/v1"
	"github.com/codeharik/Atlantic/sandslash/api/product/v1/v1connect"
)

type Service struct {
	v1connect.UnimplementedProductServiceHandler
	querier *Queries
}

func (s *Service) GetCategoryPath(ctx context.Context, req *connect.Request[pb.GetCategoryPathRequest]) (*connect.Response[pb.GetCategoryPathResponse], error) {
	id := req.Msg.GetId()

	result, err := s.querier.GetCategoryPath(ctx, id)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "GetCategoryPath")
		return nil, err
	}
	return connect.NewResponse(&pb.GetCategoryPathResponse{Value: result}), nil
}

func (s *Service) GetProductWithCategoryPath(ctx context.Context, req *connect.Request[pb.GetProductWithCategoryPathRequest]) (*connect.Response[pb.GetProductWithCategoryPathResponse], error) {
	id := req.Msg.GetId()

	result, err := s.querier.GetProductWithCategoryPath(ctx, id)
	if err != nil {
		slog.Error("sql call failed", "error", err, "method", "GetProductWithCategoryPath")
		return nil, err
	}
	return connect.NewResponse(&pb.GetProductWithCategoryPathResponse{GetProductWithCategoryPathRow: toGetProductWithCategoryPathRow(result)}), nil
}
