apiVersion: v1
kind: Namespace
metadata:
   name: cilium-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: cilium-gateway
   namespace: argocd
spec:
   project: default
   source:
      repoURL: https://helm.cilium.io/
      targetRevision: 1.17.0-pre.0
      chart: cilium
      helm:
         releaseName: cilium
   destination:
      server: "https://kubernetes.default.svc"
      namespace: cilium-system
   syncPolicy:
      automated:
         prune: true
         selfHeal: true
