apiVersion: v1
kind: Namespace
metadata:
   name: headlamp

---
apiVersion: v1
kind: ServiceAccount
metadata:
   name: headlamp-admin
   namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
   name: headlamp-admin-binding
subjects:
   - kind: ServiceAccount
     name: headlamp-admin
     namespace: kube-system
roleRef:
   kind: ClusterRole
   name: cluster-admin
   apiGroup: rbac.authorization.k8s.io

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: headlamp-system
   namespace: argocd
spec:
   project: default
   source:
      repoURL: https://headlamp-k8s.github.io/headlamp/
      targetRevision: 0.25.0
      chart: headlamp
      helm:
         releaseName: headlamp
   destination:
      server: "https://kubernetes.default.svc"
      namespace: headlamp
   syncPolicy:
      automated:
         prune: true
         selfHeal: true
