apiVersion: v1
kind: Namespace
metadata:
   name: pgatlantic

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: postgresql-system
   namespace: argocd
spec:
   project: default
   source:
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 15.5.32
      chart: postgresql
      helm:
         releaseName: postgresql
         values: |
            global:
               postgresql:
                  auth:
                     database: test
                     password: secret
                     username: superuser
            auth:
               database: test
               password: secret
               username: superuser
   destination:
      server: "https://kubernetes.default.svc"
      namespace: pgatlantic
   syncPolicy:
      automated:
         prune: true
         selfHeal: true
