apiVersion: v1
kind: Namespace
metadata:
   name: postgresql-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: postgresql-system
   namespace: argocd
spec:
   project: default
   source:
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 15.5.32
      chart: postgresql
      helm:
         releaseName: postgresql
   destination:
      server: "https://kubernetes.default.svc"
      namespace: postgresql-system
   syncPolicy:
      automated:
         prune: true
         selfHeal: true
