apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "file:///k8s/chart/gateway-helm"
    path: "."
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
