apiVersion: v1
kind: Namespace
metadata:
   name: cert-manager

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: certmanager-system
   namespace: argocd
spec:
   project: default
   source:
      repoURL: https://charts.jetstack.io
      targetRevision: 1.15.3
      chart: cert-manager
      helm:
         releaseName: cert-manager
         values: |
            crds:
              enabled: true
   destination:
      server: "https://kubernetes.default.svc"
      namespace: cert-manager
   syncPolicy:
      automated:
         prune: true
         selfHeal: true
