apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-local
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "file:///k8s/chart/cert-manager"
    path: "."
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      parameters:
        - name: crds.enabled
          value: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
