apiVersion: v1
kind: Namespace
metadata:
   name: nats-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: nats-system
   namespace: argocd
spec:
   project: default
   source:
      repoURL: https://nats-io.github.io/k8s/helm/charts/
      targetRevision: 1.2.4
      chart: nats
      helm:
         releaseName: nats
   destination:
      server: "https://kubernetes.default.svc"
      namespace: nats-system
   syncPolicy:
      automated:
         prune: true
         selfHeal: true
