apiVersion: v1
kind: Namespace
metadata:
   name: minio-system

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: minio-system
   namespace: argocd
spec:
   project: default
   source:
      repoURL: https://charts.bitnami.com/bitnami
      targetRevision: 14.7.10
      chart: minio
      helm:
         releaseName: minio
   destination:
      server: "https://kubernetes.default.svc"
      namespace: minio-system
   syncPolicy:
      automated:
         prune: true
         selfHeal: true
