# apiVersion: cert-manager.io/v1
# kind: ClusterIssuer
# metadata:
#    name: selfsigned
# spec:
#    selfSigned: {}

# ---
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#    name: example-certificate
#    namespace: default
# spec:
#    secretName: example-certificate-tls
#    issuerRef:
#       name: selfsigned
#       kind: ClusterIssuer
#    commonName: argo.com
#    dnsNames:
#       - echo.com
#       - skitty.com
#       - cow.com
#       - argo.com
