apiVersion: v1
kind: Namespace
metadata:
   name: atlantic-gateway
   namespace: atlantic-gateway
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
   name: atlantic-gateway-class
spec:
   controllerName: gateway.envoyproxy.io/gatewayclass-controller

---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
   name: atlantic-gateway
   namespace: atlantic-gateway
spec:
   gatewayClassName: atlantic-gateway-class
   listeners:
      - name: http
        protocol: HTTP
        port: 80
        allowedRoutes:
           namespaces:
              from: All
      # - port: 443
      #   protocol: HTTPS
      #   name: https
      #   tls:
      #      mode: Terminate
      #      certificateRefs:
      #         - name: example-certificate-tls
