apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: cilium-gateway
spec:
  controllerName: "io.cilium/gateway-controller"

---

apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: my-gateway
  namespace: atlantic
spec:
  gatewayClassName: cilium-gateway
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    routes:
      kind: HTTPRoute
      selector:
        matchLabels:
          gateway: my-gateway

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nextjs-app-route
  namespace: atlantic
  labels:
    gateway: my-gateway
spec:
  parentRefs:
  - name: my-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/"
    forwardTo:
    - serviceName: skitty
      port: 3000

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cosmog-service-route
  namespace: atlantic
  labels:
    gateway: my-gateway
spec:
  parentRefs:
  - name: my-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: "/cosmog.v1.CosmogService/"
    forwardTo:
    - serviceName: cosmog
      port: 7800
# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: inventory-service-route
#   namespace: atlantic
#   labels:
#     gateway: my-gateway
# spec:
#   parentRefs:
#   - name: my-gateway
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: "/inventory.v1.InventoryService/"
#     forwardTo:
#     - serviceName: inventory
#       port: 9100
# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: profile-service-route
#   namespace: atlantic
#   labels:
#     gateway: my-gateway
# spec:
#   parentRefs:
#   - name: my-gateway
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: "/profile.v1.ProfileService/"
#     forwardTo:
#     - serviceName: auth
#       port: 7777
# ---
# apiVersion: gateway.networking.k8s.io/v1beta1
# kind: HTTPRoute
# metadata:
#   name: auth-service-route
#   namespace: atlantic
#   labels:
#     gateway: my-gateway
# spec:
#   parentRefs:
#   - name: my-gateway
#   rules:
#   - matches:
#     - path:
#         type: PathPrefix
#         value: "/auth.v1.AuthService/"
#     forwardTo:
#     - serviceName: auth
#       port: 7777
