// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: product/v1/product.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_product_v1_product_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{0}
}

func (x *CreateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CreateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateProductRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateProductRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_product_v1_product_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{1}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_product_v1_product_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_product_v1_product_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{3}
}

type GetProductsByIdsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dollar_1      []string               `protobuf:"bytes,1,rep,name=dollar_1,json=dollar1,proto3" json:"dollar_1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIdsRequest) Reset() {
	*x = GetProductsByIdsRequest{}
	mi := &file_product_v1_product_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIdsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIdsRequest) ProtoMessage() {}

func (x *GetProductsByIdsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIdsRequest.ProtoReflect.Descriptor instead.
func (*GetProductsByIdsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductsByIdsRequest) GetDollar_1() []string {
	if x != nil {
		return x.Dollar_1
	}
	return nil
}

type GetProductsByIdsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Product             `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductsByIdsResponse) Reset() {
	*x = GetProductsByIdsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductsByIdsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductsByIdsResponse) ProtoMessage() {}

func (x *GetProductsByIdsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductsByIdsResponse.ProtoReflect.Descriptor instead.
func (*GetProductsByIdsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductsByIdsResponse) GetList() []*Product {
	if x != nil {
		return x.List
	}
	return nil
}

type GooseDbVersion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	VersionId     int64                  `protobuf:"varint,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	IsApplied     bool                   `protobuf:"varint,3,opt,name=is_applied,json=isApplied,proto3" json:"is_applied,omitempty"`
	Tstamp        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=tstamp,proto3" json:"tstamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GooseDbVersion) Reset() {
	*x = GooseDbVersion{}
	mi := &file_product_v1_product_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GooseDbVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GooseDbVersion) ProtoMessage() {}

func (x *GooseDbVersion) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GooseDbVersion.ProtoReflect.Descriptor instead.
func (*GooseDbVersion) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{6}
}

func (x *GooseDbVersion) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GooseDbVersion) GetVersionId() int64 {
	if x != nil {
		return x.VersionId
	}
	return 0
}

func (x *GooseDbVersion) GetIsApplied() bool {
	if x != nil {
		return x.IsApplied
	}
	return false
}

func (x *GooseDbVersion) GetTstamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Tstamp
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_product_v1_product_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ListProductsRow     `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_product_v1_product_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{8}
}

func (x *ListProductsResponse) GetList() []*ListProductsRow {
	if x != nil {
		return x.List
	}
	return nil
}

type ListProductsRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRow) Reset() {
	*x = ListProductsRow{}
	mi := &file_product_v1_product_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRow) ProtoMessage() {}

func (x *ListProductsRow) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRow.ProtoReflect.Descriptor instead.
func (*ListProductsRow) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductsRow) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ListProductsRow) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ListProductsRow) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	PaymentStatus string                 `protobuf:"bytes,7,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_product_v1_product_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{10}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Order) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderitemId   string                 `protobuf:"bytes,1,opt,name=orderitem_id,json=orderitemId,proto3" json:"orderitem_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_product_v1_product_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{11}
}

func (x *OrderItem) GetOrderitemId() string {
	if x != nil {
		return x.OrderitemId
	}
	return ""
}

func (x *OrderItem) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderItem) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_product_v1_product_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{12}
}

func (x *Product) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Product) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Product) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         int32                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_product_v1_product_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateProductRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateProductRequest) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateProductPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductPriceRequest) Reset() {
	*x = UpdateProductPriceRequest{}
	mi := &file_product_v1_product_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductPriceRequest) ProtoMessage() {}

func (x *UpdateProductPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductPriceRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductPriceRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateProductPriceRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type UpdateProductPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductPriceResponse) Reset() {
	*x = UpdateProductPriceResponse{}
	mi := &file_product_v1_product_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductPriceResponse) ProtoMessage() {}

func (x *UpdateProductPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductPriceResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductPriceResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateProductPriceResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductQuantityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductQuantityRequest) Reset() {
	*x = UpdateProductQuantityRequest{}
	mi := &file_product_v1_product_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductQuantityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductQuantityRequest) ProtoMessage() {}

func (x *UpdateProductQuantityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductQuantityRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductQuantityRequest) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateProductQuantityRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *UpdateProductQuantityRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type UpdateProductQuantityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductQuantityResponse) Reset() {
	*x = UpdateProductQuantityResponse{}
	mi := &file_product_v1_product_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductQuantityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductQuantityResponse) ProtoMessage() {}

func (x *UpdateProductQuantityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductQuantityResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductQuantityResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateProductQuantityResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_product_v1_product_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	UserId        string                  `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Email         *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Verified      bool                    `protobuf:"varint,5,opt,name=verified,proto3" json:"verified,omitempty"`
	PhoneNumber   *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Gender        *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Role          int64                   `protobuf:"varint,8,opt,name=role,proto3" json:"role,omitempty"`
	DateOfBirth   *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Address       string                  `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Balance       int32                   `protobuf:"varint,11,opt,name=balance,proto3" json:"balance,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_product_v1_product_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_product_v1_product_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_product_v1_product_proto_rawDescGZIP(), []int{19}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetUsername() *wrapperspb.StringValue {
	if x != nil {
		return x.Username
	}
	return nil
}

func (x *User) GetPasswordHash() *wrapperspb.StringValue {
	if x != nil {
		return x.PasswordHash
	}
	return nil
}

func (x *User) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *User) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *User) GetPhoneNumber() *wrapperspb.StringValue {
	if x != nil {
		return x.PhoneNumber
	}
	return nil
}

func (x *User) GetGender() *wrapperspb.StringValue {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *User) GetRole() int64 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *User) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *User) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *User) GetBalance() int32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_product_v1_product_proto protoreflect.FileDescriptor

const file_product_v1_product_proto_rawDesc = "" +
	"\n" +
	"\x18product/v1/product.proto\x12\n" +
	"product.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x99\x01\n" +
	"\x14CreateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"F\n" +
	"\x15CreateProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"5\n" +
	"\x14DeleteProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"\x17\n" +
	"\x15DeleteProductResponse\"4\n" +
	"\x17GetProductsByIdsRequest\x12\x19\n" +
	"\bdollar_1\x18\x01 \x03(\tR\adollar1\"C\n" +
	"\x18GetProductsByIdsResponse\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.product.v1.ProductR\x04list\"\x92\x01\n" +
	"\x0eGooseDbVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\x03R\tversionId\x12\x1d\n" +
	"\n" +
	"is_applied\x18\x03 \x01(\bR\tisApplied\x122\n" +
	"\x06tstamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x06tstamp\"+\n" +
	"\x13ListProductsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"G\n" +
	"\x14ListProductsResponse\x12/\n" +
	"\x04list\x18\x01 \x03(\v2\x1b.product.v1.ListProductsRowR\x04list\"b\n" +
	"\x0fListProductsRow\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\"\x86\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0epayment_status\x18\a \x01(\tR\rpaymentStatus\"\x9a\x01\n" +
	"\tOrderItem\x12!\n" +
	"\forderitem_id\x18\x01 \x01(\tR\vorderitemId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x05R\x05price\"\x8c\x01\n" +
	"\aProduct\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x05R\x05price\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\"g\n" +
	"\x14UpdateProductRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x05R\x05price\":\n" +
	"\x19UpdateProductPriceRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"K\n" +
	"\x1aUpdateProductPriceResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"Y\n" +
	"\x1cUpdateProductQuantityRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"N\n" +
	"\x1dUpdateProductQuantityResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"F\n" +
	"\x15UpdateProductResponse\x12-\n" +
	"\aproduct\x18\x01 \x01(\v2\x13.product.v1.ProductR\aproduct\"\xe1\x04\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x128\n" +
	"\busername\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\busername\x12A\n" +
	"\rpassword_hash\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\fpasswordHash\x122\n" +
	"\x05email\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05email\x12\x1a\n" +
	"\bverified\x18\x05 \x01(\bR\bverified\x12?\n" +
	"\fphone_number\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\vphoneNumber\x124\n" +
	"\x06gender\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x06gender\x12\x12\n" +
	"\x04role\x18\b \x01(\x03R\x04role\x12>\n" +
	"\rdate_of_birth\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vdateOfBirth\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x18\n" +
	"\abalance\x18\v \x01(\x05R\abalance\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt2\xa5\x05\n" +
	"\x0eProductService\x12V\n" +
	"\rCreateProduct\x12 .product.v1.CreateProductRequest\x1a!.product.v1.CreateProductResponse\"\x00\x12V\n" +
	"\rDeleteProduct\x12 .product.v1.DeleteProductRequest\x1a!.product.v1.DeleteProductResponse\"\x00\x12_\n" +
	"\x10GetProductsByIds\x12#.product.v1.GetProductsByIdsRequest\x1a$.product.v1.GetProductsByIdsResponse\"\x00\x12S\n" +
	"\fListProducts\x12\x1f.product.v1.ListProductsRequest\x1a .product.v1.ListProductsResponse\"\x00\x12V\n" +
	"\rUpdateProduct\x12 .product.v1.UpdateProductRequest\x1a!.product.v1.UpdateProductResponse\"\x00\x12e\n" +
	"\x12UpdateProductPrice\x12%.product.v1.UpdateProductPriceRequest\x1a&.product.v1.UpdateProductPriceResponse\"\x00\x12n\n" +
	"\x15UpdateProductQuantity\x12(.product.v1.UpdateProductQuantityRequest\x1a).product.v1.UpdateProductQuantityResponse\"\x00B\x9e\x01\n" +
	"\x0ecom.product.v1B\fProductProtoP\x01Z5github.com/codeharik/Atlantic/database/api/product/v1\xa2\x02\x03PXX\xaa\x02\n" +
	"Product.V1\xca\x02\n" +
	"Product\\V1\xe2\x02\x16Product\\V1\\GPBMetadata\xea\x02\vProduct::V1b\x06proto3"

var (
	file_product_v1_product_proto_rawDescOnce sync.Once
	file_product_v1_product_proto_rawDescData []byte
)

func file_product_v1_product_proto_rawDescGZIP() []byte {
	file_product_v1_product_proto_rawDescOnce.Do(func() {
		file_product_v1_product_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_product_v1_product_proto_rawDesc), len(file_product_v1_product_proto_rawDesc)))
	})
	return file_product_v1_product_proto_rawDescData
}

var file_product_v1_product_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_product_v1_product_proto_goTypes = []any{
	(*CreateProductRequest)(nil),          // 0: product.v1.CreateProductRequest
	(*CreateProductResponse)(nil),         // 1: product.v1.CreateProductResponse
	(*DeleteProductRequest)(nil),          // 2: product.v1.DeleteProductRequest
	(*DeleteProductResponse)(nil),         // 3: product.v1.DeleteProductResponse
	(*GetProductsByIdsRequest)(nil),       // 4: product.v1.GetProductsByIdsRequest
	(*GetProductsByIdsResponse)(nil),      // 5: product.v1.GetProductsByIdsResponse
	(*GooseDbVersion)(nil),                // 6: product.v1.GooseDbVersion
	(*ListProductsRequest)(nil),           // 7: product.v1.ListProductsRequest
	(*ListProductsResponse)(nil),          // 8: product.v1.ListProductsResponse
	(*ListProductsRow)(nil),               // 9: product.v1.ListProductsRow
	(*Order)(nil),                         // 10: product.v1.Order
	(*OrderItem)(nil),                     // 11: product.v1.OrderItem
	(*Product)(nil),                       // 12: product.v1.Product
	(*UpdateProductRequest)(nil),          // 13: product.v1.UpdateProductRequest
	(*UpdateProductPriceRequest)(nil),     // 14: product.v1.UpdateProductPriceRequest
	(*UpdateProductPriceResponse)(nil),    // 15: product.v1.UpdateProductPriceResponse
	(*UpdateProductQuantityRequest)(nil),  // 16: product.v1.UpdateProductQuantityRequest
	(*UpdateProductQuantityResponse)(nil), // 17: product.v1.UpdateProductQuantityResponse
	(*UpdateProductResponse)(nil),         // 18: product.v1.UpdateProductResponse
	(*User)(nil),                          // 19: product.v1.User
	(*timestamppb.Timestamp)(nil),         // 20: google.protobuf.Timestamp
	(*wrapperspb.StringValue)(nil),        // 21: google.protobuf.StringValue
}
var file_product_v1_product_proto_depIdxs = []int32{
	12, // 0: product.v1.CreateProductResponse.product:type_name -> product.v1.Product
	12, // 1: product.v1.GetProductsByIdsResponse.list:type_name -> product.v1.Product
	20, // 2: product.v1.GooseDbVersion.tstamp:type_name -> google.protobuf.Timestamp
	9,  // 3: product.v1.ListProductsResponse.list:type_name -> product.v1.ListProductsRow
	20, // 4: product.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	20, // 5: product.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	12, // 6: product.v1.UpdateProductPriceResponse.product:type_name -> product.v1.Product
	12, // 7: product.v1.UpdateProductQuantityResponse.product:type_name -> product.v1.Product
	12, // 8: product.v1.UpdateProductResponse.product:type_name -> product.v1.Product
	21, // 9: product.v1.User.username:type_name -> google.protobuf.StringValue
	21, // 10: product.v1.User.password_hash:type_name -> google.protobuf.StringValue
	21, // 11: product.v1.User.email:type_name -> google.protobuf.StringValue
	21, // 12: product.v1.User.phone_number:type_name -> google.protobuf.StringValue
	21, // 13: product.v1.User.gender:type_name -> google.protobuf.StringValue
	20, // 14: product.v1.User.date_of_birth:type_name -> google.protobuf.Timestamp
	20, // 15: product.v1.User.created_at:type_name -> google.protobuf.Timestamp
	20, // 16: product.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 17: product.v1.ProductService.CreateProduct:input_type -> product.v1.CreateProductRequest
	2,  // 18: product.v1.ProductService.DeleteProduct:input_type -> product.v1.DeleteProductRequest
	4,  // 19: product.v1.ProductService.GetProductsByIds:input_type -> product.v1.GetProductsByIdsRequest
	7,  // 20: product.v1.ProductService.ListProducts:input_type -> product.v1.ListProductsRequest
	13, // 21: product.v1.ProductService.UpdateProduct:input_type -> product.v1.UpdateProductRequest
	14, // 22: product.v1.ProductService.UpdateProductPrice:input_type -> product.v1.UpdateProductPriceRequest
	16, // 23: product.v1.ProductService.UpdateProductQuantity:input_type -> product.v1.UpdateProductQuantityRequest
	1,  // 24: product.v1.ProductService.CreateProduct:output_type -> product.v1.CreateProductResponse
	3,  // 25: product.v1.ProductService.DeleteProduct:output_type -> product.v1.DeleteProductResponse
	5,  // 26: product.v1.ProductService.GetProductsByIds:output_type -> product.v1.GetProductsByIdsResponse
	8,  // 27: product.v1.ProductService.ListProducts:output_type -> product.v1.ListProductsResponse
	18, // 28: product.v1.ProductService.UpdateProduct:output_type -> product.v1.UpdateProductResponse
	15, // 29: product.v1.ProductService.UpdateProductPrice:output_type -> product.v1.UpdateProductPriceResponse
	17, // 30: product.v1.ProductService.UpdateProductQuantity:output_type -> product.v1.UpdateProductQuantityResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_product_v1_product_proto_init() }
func file_product_v1_product_proto_init() {
	if File_product_v1_product_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_product_v1_product_proto_rawDesc), len(file_product_v1_product_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_product_v1_product_proto_goTypes,
		DependencyIndexes: file_product_v1_product_proto_depIdxs,
		MessageInfos:      file_product_v1_product_proto_msgTypes,
	}.Build()
	File_product_v1_product_proto = out.File
	file_product_v1_product_proto_goTypes = nil
	file_product_v1_product_proto_depIdxs = nil
}
