// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file user/v1/user.proto (package user.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateUserRequest, CreateUserResponse, DeleteUserRequest, DeleteUserResponse, FindUserByUsernameRequest, FindUserByUsernameResponse, GetUserByIDRequest, GetUserByIDResponse, ListUsersRequest, ListUsersResponse, UpdateUserRequest, UpdateUserResponse } from "./user_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service user.v1.UserService
 */
export const UserService = {
  typeName: "user.v1.UserService",
  methods: {
    /**
     * @generated from rpc user.v1.UserService.CreateUser
     */
    createUser: {
      name: "CreateUser",
      I: CreateUserRequest,
      O: CreateUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserService.DeleteUser
     */
    deleteUser: {
      name: "DeleteUser",
      I: DeleteUserRequest,
      O: DeleteUserResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserService.FindUserByUsername
     */
    findUserByUsername: {
      name: "FindUserByUsername",
      I: FindUserByUsernameRequest,
      O: FindUserByUsernameResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserService.GetUserByID
     */
    getUserByID: {
      name: "GetUserByID",
      I: GetUserByIDRequest,
      O: GetUserByIDResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserService.ListUsers
     */
    listUsers: {
      name: "ListUsers",
      I: ListUsersRequest,
      O: ListUsersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc user.v1.UserService.UpdateUser
     */
    updateUser: {
      name: "UpdateUser",
      I: UpdateUserRequest,
      O: UpdateUserResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

