// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file cart/v1/cart.proto (package cart.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CreateCartItemRequest, CreateCartItemResponse, CreateCartRequest, CreateCartResponse, DeleteCartByIDRequest, DeleteCartByIDResponse, DeleteCartItemByIDRequest, DeleteCartItemByIDResponse, GetCartByIDRequest, GetCartByIDResponse, GetCartItemByIDRequest, GetCartItemByIDResponse, GetCartItemsByCartIDRequest, GetCartItemsByCartIDResponse, GetCartsByUserIDRequest, GetCartsByUserIDResponse, UpdateCartItemQuantityRequest, UpdateCartItemQuantityResponse } from "./cart_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service cart.v1.CartService
 */
export const CartService = {
  typeName: "cart.v1.CartService",
  methods: {
    /**
     * @generated from rpc cart.v1.CartService.CreateCart
     */
    createCart: {
      name: "CreateCart",
      I: CreateCartRequest,
      O: CreateCartResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.CreateCartItem
     */
    createCartItem: {
      name: "CreateCartItem",
      I: CreateCartItemRequest,
      O: CreateCartItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.DeleteCartByID
     */
    deleteCartByID: {
      name: "DeleteCartByID",
      I: DeleteCartByIDRequest,
      O: DeleteCartByIDResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.DeleteCartItemByID
     */
    deleteCartItemByID: {
      name: "DeleteCartItemByID",
      I: DeleteCartItemByIDRequest,
      O: DeleteCartItemByIDResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.GetCartByID
     */
    getCartByID: {
      name: "GetCartByID",
      I: GetCartByIDRequest,
      O: GetCartByIDResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.GetCartItemByID
     */
    getCartItemByID: {
      name: "GetCartItemByID",
      I: GetCartItemByIDRequest,
      O: GetCartItemByIDResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.GetCartItemsByCartID
     */
    getCartItemsByCartID: {
      name: "GetCartItemsByCartID",
      I: GetCartItemsByCartIDRequest,
      O: GetCartItemsByCartIDResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.GetCartsByUserID
     */
    getCartsByUserID: {
      name: "GetCartsByUserID",
      I: GetCartsByUserIDRequest,
      O: GetCartsByUserIDResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.UpdateCartItemQuantity
     */
    updateCartItemQuantity: {
      name: "UpdateCartItemQuantity",
      I: UpdateCartItemQuantityRequest,
      O: UpdateCartItemQuantityResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

