// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file cart/v1/cart.proto (package cart.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Cart, CartItem, CheckoutCartRequest, CheckoutCartResponse, CreateCartRequest, GetCartRequest } from "./cart_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * rpc PlaceOrder(PlaceOrderRequest) returns (PlaceOrderResponse);
 *
 * @generated from service cart.v1.CartService
 */
export const CartService = {
  typeName: "cart.v1.CartService",
  methods: {
    /**
     * @generated from rpc cart.v1.CartService.CreateCart
     */
    createCart: {
      name: "CreateCart",
      I: CreateCartRequest,
      O: Cart,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.GetCart
     */
    getCart: {
      name: "GetCart",
      I: GetCartRequest,
      O: Cart,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.UpdateCartItem
     */
    updateCartItem: {
      name: "UpdateCartItem",
      I: CartItem,
      O: Cart,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cart.v1.CartService.CheckoutCart
     */
    checkoutCart: {
      name: "CheckoutCart",
      I: CheckoutCartRequest,
      O: CheckoutCartResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

